In [45]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from uszipcode import SearchEngine
import geocoder

# Census API Key
from config import api_key
c = Census(api_key, year=2017)

In [35]:
# Run Census Search to retrieve data on all zip codes (2013 ACS5 Census)
# See: https://github.com/CommerceDataService/census-wrapper for library documentation
# See: https://gist.github.com/afhaque/60558290d6efd892351c4b64e5c01e9b for labels
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E"), {'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})

# Add in Poverty Rate (Poverty Count / Population)
census_pd["Poverty Rate"] = 100 * \
    census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

# Final DataFrame
census_pd = census_pd[["Zipcode", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Poverty Count", "Poverty Rate"]]

# Visualize
print(len(census_pd))
census_pd.head()

33120

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate
0,00601,17599.0,38.9,11757.0,7041.0,11282.0,64.105915
1,00602,39209.0,40.9,16190.0,8978.0,20428.0,52.100283
2,00603,50135.0,40.4,16645.0,10897.0,25176.0,50.216416
3,00606,6304.0,42.8,13387.0,5960.0,4092.0,64.911168
4,00610,27590.0,41.4,18741.0,9266.0,12553.0,45.498369

In [36]:
sort_by_zip = census_pd.sort_values('Zipcode', ascending=True)
sort_by_zip

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate
0,00601,17599.0,38.9,11757.0,7041.0,11282.0,64.105915
1,00602,39209.0,40.9,16190.0,8978.0,20428.0,52.100283
2,00603,50135.0,40.4,16645.0,10897.0,25176.0,50.216416
3,00606,6304.0,42.8,13387.0,5960.0,4092.0,64.911168
4,00610,27590.0,41.4,18741.0,9266.0,12553.0,45.498369
5,00612,62566.0,41.4,17744.0,10283.0,29872.0,47.744782
6,00616,10687.0,43.7,14918.0,9002.0,5364.0,50.191822
7,00617,24508.0,38.7,17157.0,8762.0,11774.0,48.041456
8,00622,7405.0,48.4,16727.0,11935.0,4013.0,54.193113
9,00623,42321.0,41.3,16401.0,9101.0,22008.0,52.002552
10,00624,23238.0,37.2,16832.0,8072.0,13092.0,56.338755
11,00627,32936.0,40.1,17579.0,9738.0,15927.0,48.357420
12,00631,1555.0,48.2,9632.0,7690.0,922.0,59.292605
13,00637,23610.0,40.9,15736.0,9158.0,11506.0,48.733587
14,00638,17202.0,40.3,14448.0,8108.0,9961.0,57.906057
15,00641,28332.0,41.9,16292.0,8305.0,14903.0,52.601299
16,00646,38008.0,39.4,29160.0,15397.0,12709.0,33.437697
17,00647,5610.0,47.1,13071.0,7058.0,3551.0,63.297683
18,00650,14664.0,38.6,16095.0,7698.0,8200.0,55.919258
19,00652,3681.0,38.8,20564.0,11439.0,1597.0,43.384950
20,00653,11717.0,38.7,12236.0,7279.0,7737.0,66.032261
21,00656,19546.0,40.3,14966.0,8327.0,10869.0,55.607285
22,00659,40978.0,40.7,17770.0,10360.0,18522.0,45.199863
23,00660,16474.0,45.1,19674.0,11588.0,6476.0,39.310429
24,00662,41341.0,40.6,16771.0,8883.0,21976.0,53.157882
25,00664,15396.0,36.3,15401.0,7134.0,9164.0,59.521954
26,00667,24089.0,43.6,13843.0,7256.0,14529.0,60.313836
27,00669,26510.0,40.9,12996.0,8236.0,14802.0,55.835534
28,00670,8797.0,40.1,14456.0,7293.0,4982.0,56.632943
29,00674,40826.0,41.1,18032.0,10520.0,18834.0,46.132367
...,...,...,...,...,...,...,...
33090,99786,299.0,26.9,44500.0,15937.0,83.0,27.759197
33091,99788,119.0,34.4,28750.0,19081.0,41.0,34.453782
33092,99789,395.0,25.4,82813.0,22481.0,36.0,9.113924
33093,99790,7.0,-666666666.0,-666666666.0,NaN,0.0,0.000000
33094,99791,172.0,24.5,61250.0,20597.0,33.0,19.186047
33095,99801,30179.0,38.2,91743.0,41968.0,2006.0,6.647006
33096,99820,540.0,42.7,36000.0,34954.0,113.0,20.925926
33097,99824,2255.0,35.5,75577.0,41057.0,333.0,14.767184
33098,99825,89.0,58.5,88500.0,50983.0,0.0,0.000000
33099,99826,386.0,53.3,61875.0,39582.0,14.0,3.626943
33100,99827,2599.0,45.5,70091.0,35619.0,214.0,8.233936
33101,99829,828.0,46.1,60625.0,28857.0,98.0,11.835749
33102,99830,635.0,37.2,51250.0,18955.0,97.0,15.275591
33103,99832,94.0,55.5,67917.0,33720.0,6.0,6.382979
33104,99833,3275.0,41.7,63490.0,35044.0,256.0,7.816794
33105,99835,8810.0,38.9,70765.0,36617.0,800.0,9.080590
33106,99836,60.0,40.7,66875.0,30355.0,0.0,0.000000
33107,99840,1038.0,42.9,70673.0,39376.0,58.0,5.587669
33108,99841,147.0,61.3,59688.0,34670.0,3.0,2.040816
33109,99901,13768.0,39.5,67321.0,33755.0,1450.0,10.531668
33110,99903,20.0,-666666666.0,-666666666.0,NaN,11.0,55.000000
33111,99918,174.0,57.8,63125.0,34149.0,0.0,0.000000
33112,99919,660.0,47.8,50956.0,31413.0,56.0,8.484848
33113,99921,1971.0,41.1,58047.0,33002.0,286.0,14.510401
33114,99922,306.0,45.0,31250.0,16408.0,92.0,30.065359
33115,99923,0.0,-666666666.0,-666666666.0,-666666666.0,0.0,NaN
33116,99925,901.0,45.1,48646.0,24783.0,210.0,23.307436
33117,99926,1684.0,32.8,57969.0,22927.0,224.0,13.301663
33118,99927,59.0,49.8,17981.0,11959.0,49.0,83.050847
33119,99929,2455.0,49.0,55742.0,29861.0,276.0,11.242363

In [37]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_pd.to_csv("hunger.csv", encoding="utf-8", index=False)

In [38]:
zip_poverty_df = census_pd[["Zipcode", "Poverty Rate"]]
zip_poverty_df.head()

  Zipcode  Poverty Rate
0   00601     64.105915
1   00602     52.100283
2   00603     50.216416
3   00606     64.911168
4   00610     45.498369

In [39]:
print(len(zip_poverty_df))

33120

In [40]:
zip_poverty_df.dtypes

Zipcode          object
Poverty Rate    float64
dtype: object

In [41]:
search = SearchEngine(simple_zipcode=True)

In [47]:
eustis = search.by_zipcode("32726")
eustis

SimpleZipcode(zipcode='32726', zipcode_type='Standard', major_city='Eustis', post_office_city='Eustis, FL', common_city_list=['Eustis'], county='Lake County', state='FL', lat=28.86, lng=-81.69, timezone='Eastern', radius_in_miles=3.0, area_code_list=['352'], population=20029, population_density=1640.0, land_area_in_sqmi=12.22, water_area_in_sqmi=1.67, housing_units=9628, occupied_housing_units=8158, median_home_value=118000, median_household_income=36376, bounds_west=-81.728986, bounds_east=-81.643515, bounds_north=28.898251, bounds_south=28.819952)

In [51]:
zip_df = pd.DataFrame({
    
    "zipcode": ["Ornate", "Classical", "Modern", "Wood", "Cardboard"],
    
    "lat": [15.00, 12.50, 10.00, 5.00, 1.00],
    
    "lng": [100, 200, 150, 300, "N/A"]})

zip_df

SyntaxError: invalid syntax (<ipython-input-51-e9f14792852d>, line 2)

In [ ]:
zipcode.to_json()

In [ ]:
for zipcode in zip_poverty_df.Zipcode:
    print(zipcode)

In [ ]:
# def get_geocoder(zip_poverty_df):
#      # initialize your variable to None
#      lat_lng_coords = None
#      # loop until you get the coordinates
#      while(lat_lng_coords is None):
#        g = geocoder.google('00652')
#        lat_lng_coords = g.latlng
#      latitude = lat_lng_coords[0]
#      longitude = lat_lng_coords[1]
#      return latitude,longitude

# for i in range(0,len(zip_poverty_df)):
#     zip_poverty_df['Latitude'][i],zip_poverty_df['Longitude'][i]=get_geocoder(zip_poverty_df.iloc[i]['Zipcode'])
    
#    # post_df['Latitude'], post_df['Longitude'] = zip(*post_df['Postcode'].apply(get_geocoder))

In [ ]:
zip_only_df = zip_poverty_df["Zipcode"]
zip_only_df.head()

In [ ]:
drop_na_df = zip_only_df.dropna()
drop_na_df

In [ ]:
print(len(drop_na_df))

In [ ]:
#gmaps.configure(api_key="AIzaSyCUGxOSyCpiom_dAlxYwQHVUUBeykyNePw")

In [ ]:
lat = []
lon = []

for zipcode in zipcode:
    try:
        lat.append(float([0]))
        lon.append(float([1]))
    except:
        lat.append(np.NaN)
        lon.append(np.NaN)

drop_na_df['latitude'] = lat
drop_na_df['longitude'] = lon